services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - POST=1
    networks:
      n8n-shared-network:
        aliases:
          - dockerproxy

networks:
  n8n-shared-network:
    external: true
