services:
  n8n:
    image: n8nio/n8n:latest
    environment:
      WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      N8N_HOST: ${N8N_HOST}
      GENERIC_TIMEZONE: ${N8N_GENERIC_TIMEZONE:-America/Sao_Paulo}
      N8N_LOG_LEVEL: ${N8N_LOG_LEVEL:-debug}
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      N8N_SECURE_COOKIE: false
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: default
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD:-default}
      DB_POSTGRESDB_POOL_SIZE: 10
      N8N_EMAIL_MODE: smtp
      N8N_SMTP_HOST: ${N8N_SMTP_HOST:-any}
      N8N_SMTP_PORT: ${N8N_SMTP_PORT:-465}
      N8N_SMTP_USER: ${N8N_SMTP_USER:-apikey}
      N8N_SMTP_PASS: ${N8N_SMTP_PASS:-pass}
      N8N_SMTP_SENDER: ${N8N_SMTP_SENDER:-any}
      N8N_SMTP_SSL: true
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "${N8N_PORT:-5678}:5678"
    networks:
      - n8n-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default}
      POSTGRES_DB: ${POSTGRES_DB:-default}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - n8n-network

  redis:
    image: redis:latest
    command: redis-server --requirepass default
    environment:
      REDIS_USER: default
      REDIS_PASSWORD: ${REDIS_PASSWORD:-default}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - n8n-network

  pgadmin4:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    networks:
      - n8n-network

volumes:
  n8n_data:
  pg_data:
  pgadmin4_data:

networks:
  n8n-network: {}

